0,org.assertj.core.api.future.CompletableFutureAssert_hasNotFailed_Test:should_fail_if_completable_future_has_failed
0,org.assertj.core.api.future.CompletableFutureAssert_hasNotFailed_Test:should_fail_when_completable_future_is_null
0,org.assertj.core.api.WithAssertions_delegation_Test:withAssertions_assertThatThrownBy_Test
0,org.assertj.core.api.future.CompletableFutureAssert_isNotDone_Test:should_fail_when_completable_future_is_null
0,org.assertj.core.api.future.CompletableFutureAssert_isNotDone_Test:should_fail_if_completable_future_is_done
0,org.assertj.core.api.future.CompletableFutureAssert_isNotCompleted_Test:should_fail_when_completable_future_is_null
0,org.assertj.core.api.future.CompletableFutureAssert_isNotCompleted_Test:should_fail_if_completable_future_is_completed
0,org.assertj.core.navigation.ClassBasedNavigableIterable_Test:first_element_navigating_failing_test
0,org.assertj.core.navigation.ClassBasedNavigableIterable_Test:element_navigating_failing_tests
0,org.assertj.core.navigation.ClassBasedNavigableIterable_Test:last_element_navigating_failing_test
0,org.assertj.core.navigation.ClassBasedNavigableList_Test:first_element_navigating_failing_test
0,org.assertj.core.navigation.ClassBasedNavigableList_Test:element_navigating_failing_tests
0,org.assertj.core.navigation.ClassBasedNavigableList_Test:last_element_navigating_failing_test
0,org.assertj.core.api.Assertions_assertThatExceptionOfType_Test:should_create_ChainedThrowableAssert
0,org.assertj.core.api.Assertions_assertThatExceptionOfType_Test:should_pass_thrown_exception_to_ChainedThrowableAssert
0,org.assertj.core.api.BDDSoftAssertionsTest:should_be_able_to_catch_exceptions_thrown_by_all_proxied_methods
0,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:should_build_ThrowableAssert_with_throwable_thrown
0,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:should_fail_if_no_throwable_was_thrown
1,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:should_fail_if_no_throwable_was_thrown
0,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:fail_with_good_message_when_assertion_is_failing
0,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:should_build_ThrowableAssert_with_runtime_exception_thrown
0,org.assertj.core.api.future.CompletableFutureAssert_isCancelled_Test:should_fail_when_completable_future_is_null
0,org.assertj.core.api.future.CompletableFutureAssert_isCancelled_Test:should_fail_if_completable_future_is_not_cancelled
0,org.assertj.core.api.future.CompletableFutureAssert_isCompleted_Test:should_fail_if_completable_future_was_cancelled
0,org.assertj.core.api.future.CompletableFutureAssert_isCompleted_Test:should_fail_if_completable_future_has_failed
0,org.assertj.core.api.future.CompletableFutureAssert_isCompleted_Test:should_fail_when_completable_future_is_null
0,org.assertj.core.api.future.CompletableFutureAssert_isCompleted_Test:should_fail_if_completable_future_is_incomplete
0,org.assertj.core.navigation.FactoryBasedNavigableIterabelAssert_Test:first_element_navigating_failing_test
0,org.assertj.core.navigation.FactoryBasedNavigableIterabelAssert_Test:element_navigating_failing_tests
0,org.assertj.core.navigation.FactoryBasedNavigableIterabelAssert_Test:last_element_navigating_failing_test
0,org.assertj.core.api.throwable.ThrowableAssert_built_from_lambda_Test:should_fail_if_nothing_is_thrown_by_lambda
1,org.assertj.core.api.throwable.ThrowableAssert_built_from_lambda_Test:should_fail_if_nothing_is_thrown_by_lambda
0,org.assertj.core.api.throwable.ThrowableAssert_built_from_lambda_Test:should_build_ThrowableAssert_with_runtime_exception_thrown_by_lambda
0,org.assertj.core.api.throwable.ThrowableAssert_built_from_lambda_Test:should_build_ThrowableAssert_with_checked_exception_thrown_by_lambda
0,org.assertj.core.navigation.FactoryBasedNavigableListAssert_Test:first_element_navigating_failing_test
0,org.assertj.core.navigation.FactoryBasedNavigableListAssert_Test:element_navigating_failing_tests
0,org.assertj.core.navigation.FactoryBasedNavigableListAssert_Test:last_element_navigating_failing_test
0,org.assertj.core.api.future.CompletableFutureAssert_isNotCompletedExceptionally_Test:should_fail_when_completable_future_is_null
0,org.assertj.core.api.future.CompletableFutureAssert_isNotCompletedExceptionally_Test:should_fail_if_completable_future_is_not_completed_exceptionally
0,org.assertj.core.util.Introspection_getProperty_Test:should_raise_an_error_because_of_non_public_getter
0,org.assertj.core.util.Introspection_getProperty_Test:should_raise_an_error_because_of_non_public_getter_when_getter_is_in_superclass
0,org.assertj.core.util.Introspection_getProperty_Test:should_raise_an_error_because_of_missing_getter
0,org.assertj.core.api.AutoCloseableSoftAssertionsTest:should_be_able_to_catch_exceptions_thrown_by_all_proxied_methods
0,org.assertj.core.api.SoftAssertionsTest:should_assert_using_assertSoftly
0,org.assertj.core.api.SoftAssertionsTest:should_be_able_to_catch_exceptions_thrown_by_all_proxied_methods
0,org.assertj.core.api.iterable.IterableAssert_extracting_Test:should_throw_error_if_function_fails
0,org.assertj.core.api.future.CompletableFutureAssert_isCompletedExceptionally_Test:should_fail_when_completable_future_is_null
0,org.assertj.core.api.future.CompletableFutureAssert_isCompletedExceptionally_Test:should_fail_if_completable_future_is_not_completed_exceptionally
0,org.assertj.core.api.future.CompletableFutureAssert_isNotCancelled_Test:should_fail_when_completable_future_is_null
0,org.assertj.core.api.future.CompletableFutureAssert_isNotCancelled_Test:should_fail_if_completable_future_is_not_cancelled
0,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_fail_if_nothing_is_thrown_by_lambda
1,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_fail_if_nothing_is_thrown_by_lambda
0,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_build_ExpectThrowableAssert_with_exception_thrown_by_lambda
0,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
0,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_was_cancelled
0,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_when_completable_future_is_null
0,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_is_completed
0,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_is_incomplete
0,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_was_cancelled
0,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_when_completable_future_is_null
0,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_is_completed
0,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_has_failed_with_wrong_throwable
0,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_is_incomplete
0,org.assertj.core.api.throwable.ThrowableAssert_built_with_then_method_Test:should_fail_if_nothing_is_thrown_by_callable_code
1,org.assertj.core.api.throwable.ThrowableAssert_built_with_then_method_Test:should_fail_if_nothing_is_thrown_by_callable_code
0,org.assertj.core.api.throwable.ThrowableAssert_built_with_then_method_Test:should_build_ThrowableAssert_with_throwable_thrown_by_callable_code
0,org.assertj.core.api.throwable.ThrowableAssert_built_with_then_method_Test:should_build_ThrowableAssert_with_runtime_exception_thrown_by_callable_code
0,org.assertj.core.api.throwable.ThrowableAssert_built_from_ThrowingCallable_Test:should_fail_if_nothing_is_thrown_by_callable_code
1,org.assertj.core.api.throwable.ThrowableAssert_built_from_ThrowingCallable_Test:should_fail_if_nothing_is_thrown_by_callable_code
0,org.assertj.core.api.throwable.ThrowableAssert_built_from_ThrowingCallable_Test:should_build_ThrowableAssert_with_throwable_thrown_by_callable_code
0,org.assertj.core.api.throwable.ThrowableAssert_built_from_ThrowingCallable_Test:should_build_ThrowableAssert_with_runtime_exception_thrown_by_callable_code
0,org.assertj.core.api.future.CompletableFutureAssert_isDone_Test:should_fail_if_completable_future_is_not_done
0,org.assertj.core.api.future.CompletableFutureAssert_isDone_Test:should_fail_when_completable_future_is_null
