0,32,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_has_no_cause
8,42,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_has_no_cause
9,42,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_has_no_cause
10,42,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_has_no_cause
0,32,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_is_null
8,42,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_is_null
9,42,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_is_null
10,42,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_is_null
0,32,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
1,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
2,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
3,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
4,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
5,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
6,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
7,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
0,32,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
1,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
2,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
3,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
4,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
5,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
6,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
7,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
0,32,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
1,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
2,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
3,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
4,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
5,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
6,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
7,37,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
0,32,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
1,37,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
2,37,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
3,37,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
4,37,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
5,37,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
6,37,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
7,37,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
