32,org.assertj.core.internal.throwables.Throwables_assertHasCauseInstanceOf_Test:should_pass_if_cause_is_instance_of_expected_type
31,org.assertj.core.internal.throwables.Throwables_assertHasCauseInstanceOf_Test:should_fail_if_actual_has_no_cause
31,org.assertj.core.internal.throwables.Throwables_assertHasCauseInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
32,org.assertj.core.internal.throwables.Throwables_assertHasCauseInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
1,org.assertj.core.api.objectarray.ObjectArrayAssert_usingRecursiveFieldByFieldElementComparator_Test:failed_isIn_assertion_using_recursive_field_by_field_element_comparator
1,org.assertj.core.api.objectarray.ObjectArrayAssert_usingRecursiveFieldByFieldElementComparator_Test:failed_isEqualTo_assertion_using_recursive_field_by_field_element_comparator
1,org.assertj.core.api.future.CompletableFutureAssert_hasNotFailed_Test:should_fail_if_completable_future_has_failed
1,org.assertj.core.api.future.CompletableFutureAssert_hasNotFailed_Test:should_fail_when_completable_future_is_null
16,org.assertj.core.api.objectarray.ObjectArrayAssert_hasOnlyOneElementSatisfying_Test:fails_if_iterable_has_only_one_element_and_that_element_does_not_statisfy_the_soft_assertion
14,org.assertj.core.api.objectarray.ObjectArrayAssert_hasOnlyOneElementSatisfying_Test:fails_if_iterable_has_only_one_element_and_that_element_does_not_statisfy_the_soft_assertion
1,org.assertj.core.api.object.ObjectAssert_hasNoNullFieldsOrProperties_Test:should_fail_if_a_private_field_is_null
1,org.assertj.core.api.object.ObjectAssert_hasNoNullFieldsOrProperties_Test:should_fail_if_a_public_field_is_null
1,org.assertj.core.api.object.ObjectAssert_hasNoNullFieldsOrProperties_Test:should_fail_if_a_property_is_null
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isEqualToIgnoringNanoseconds_Test:should_fail_as_seconds_fields_are_different
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isEqualToIgnoringNanoseconds_Test:should_fail_if_actual_is_not_equal_to_given_offsetdatetime_with_nanoseconds_ignored
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isEqualToIgnoringSeconds_Test:should_fail_as_seconds_fields_are_different_even_if_time_difference_is_less_than_a_second
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isEqualToIgnoringSeconds_Test:should_fail_if_actual_is_not_equal_to_given_offsetdatetime_with_second_ignored
1,org.assertj.core.internal.floats.Floats_assertEqual_float_with_offset_Test:should_fail_if_second_float_is_null_but_not_the_first
1,org.assertj.core.internal.floats.Floats_assertEqual_float_with_offset_Test:should_fail_if_second_float_is_null_but_not_the_first_whatever_custom_comparison_strategy_is
1,org.assertj.core.api.WithAssertions_delegation_Test:withAssertions_assertThatThrownBy_Test
1,org.assertj.core.api.WithAssertions_delegation_Test:withAssertions_catchThrowable_Test
16,org.assertj.core.api.filter.Filter_with_property_not_equals_to_given_value_Test:should_fail_if_elements_to_filter_do_not_have_property_used_by_filter
14,org.assertj.core.api.filter.Filter_with_property_not_equals_to_given_value_Test:should_fail_if_elements_to_filter_do_not_have_property_used_by_filter
1,org.assertj.core.api.filter.Filter_with_property_not_equals_to_given_value_Test:should_fail_if_property_to_filter_on_is_null
1,org.assertj.core.api.zoneddatetime.ZonedDateTimeAssert_isIn_errors_Test:test_isIn_assertion_error_message
16,org.assertj.core.api.iterable.IterableAssert_filteredOnNull_Test:should_fail_if_on_of_the_iterable_element_does_not_have_given_property_or_field
14,org.assertj.core.api.iterable.IterableAssert_filteredOnNull_Test:should_fail_if_on_of_the_iterable_element_does_not_have_given_property_or_field
1,org.assertj.core.api.localdatetime.LocalDateTimeAssert_isAfterOrEqualTo_Test:test_isAfterOrEqual_assertion_error_message
1,org.assertj.core.api.object.ObjectAssert_hasFieldOrProperty_Test:shoud_fail_if_given_field_or_property_name_is_null
1,org.assertj.core.api.object.ObjectAssert_hasFieldOrProperty_Test:shoud_fail_if_field_or_property_does_not_exists
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isNotIn_Test:test_isNotIn_assertion_error_message
1,org.assertj.core.internal.strings.Strings_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isNotEqualTo_Test:test_isNotEqualTo_assertion_error_message
1,org.assertj.core.internal.paths.Paths_assertIsCanonical_Test:should_throw_PathsException_on_io_error
1,org.assertj.core.api.iterable.IterableAssert_usingRecursiveFieldByFieldElementComparator_Test:failed_isIn_assertion_using_recursive_field_by_field_element_comparator
1,org.assertj.core.api.iterable.IterableAssert_usingRecursiveFieldByFieldElementComparator_Test:failed_isEqualTo_assertion_using_recursive_field_by_field_element_comparator
1,org.assertj.core.api.future.CompletableFutureAssert_isNotDone_Test:should_fail_when_completable_future_is_null
1,org.assertj.core.api.future.CompletableFutureAssert_isNotDone_Test:should_fail_if_completable_future_is_done
1,org.assertj.core.api.future.CompletableFutureAssert_isNotCompleted_Test:should_fail_when_completable_future_is_null
1,org.assertj.core.api.future.CompletableFutureAssert_isNotCompleted_Test:should_fail_if_completable_future_is_completed
1,org.assertj.core.internal.iterables.Iterables_assertHasSize_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.internal.iterables.Iterables_assertHasSize_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size_whatever_custom_comparison_strategy_is
16,org.assertj.core.navigation.ClassBasedNavigableIterable_Test:first_element_navigating_failing_test
14,org.assertj.core.navigation.ClassBasedNavigableIterable_Test:first_element_navigating_failing_test
16,org.assertj.core.navigation.ClassBasedNavigableIterable_Test:element_navigating_failing_tests
14,org.assertj.core.navigation.ClassBasedNavigableIterable_Test:element_navigating_failing_tests
16,org.assertj.core.navigation.ClassBasedNavigableIterable_Test:last_element_navigating_failing_test
14,org.assertj.core.navigation.ClassBasedNavigableIterable_Test:last_element_navigating_failing_test
16,org.assertj.core.api.iterable.IterableAssert_filteredOn_notIn_Test:should_fail_if_on_of_the_iterable_element_does_not_have_given_property_or_field
14,org.assertj.core.api.iterable.IterableAssert_filteredOn_notIn_Test:should_fail_if_on_of_the_iterable_element_does_not_have_given_property_or_field
1,org.assertj.core.api.abstract_.AbstractAssert_satisfies_Test:should_fail_according_to_requirements
1,org.assertj.core.internal.longarrays.LongArrays_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.api.localdate.LocalDateAssert_isBefore_Test:test_isBefore_assertion_error_message
1,org.assertj.core.internal.doublearrays.DoubleArrays_assertHasSameSizeAs_with_Array_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
16,org.assertj.core.navigation.ClassBasedNavigableList_Test:first_element_navigating_failing_test
14,org.assertj.core.navigation.ClassBasedNavigableList_Test:first_element_navigating_failing_test
16,org.assertj.core.navigation.ClassBasedNavigableList_Test:element_navigating_failing_tests
14,org.assertj.core.navigation.ClassBasedNavigableList_Test:element_navigating_failing_tests
16,org.assertj.core.navigation.ClassBasedNavigableList_Test:last_element_navigating_failing_test
14,org.assertj.core.navigation.ClassBasedNavigableList_Test:last_element_navigating_failing_test
1,org.assertj.core.internal.chararrays.CharArrays_assertHasSameSizeAs_with_Array_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
16,org.assertj.core.api.iterable.IterableAssert_filteredOn_in_Test:should_fail_if_on_of_the_iterable_element_does_not_have_given_property_or_field
14,org.assertj.core.api.iterable.IterableAssert_filteredOn_in_Test:should_fail_if_on_of_the_iterable_element_does_not_have_given_property_or_field
1,org.assertj.core.api.localdatetime.LocalDateTimeAssert_isBefore_Test:test_isBefore_assertion_error_message
1,org.assertj.core.api.zoneddatetime.ZonedDateTimeAssert_isEqualTo_errors_Test:test_isEqualTo_assertion_error_message
0,org.assertj.core.api.BDDSoftAssertionsTest:should_be_able_to_catch_exceptions_thrown_by_all_proxied_methods
1,org.assertj.core.api.localdatetime.LocalDateTimeAssert_isAfter_Test:test_isAfter_assertion_error_message
1,org.assertj.core.api.localdate.LocalDateAssert_isBeforeOrEqualTo_Test:test_isBeforeOrEqual_assertion_error_message
1,org.assertj.core.api.optional.OptionalAssert_containsInstanceOf_Test:should_fail_if_optional_is_empty
1,org.assertj.core.api.optional.OptionalAssert_containsInstanceOf_Test:should_fail_if_optional_contains_other_type_than_required
16,org.assertj.core.api.objectarray.ObjectArrayAssert_filteredOn_Test:should_fail_if_on_of_the_object_array_element_does_not_have_given_property_or_field
14,org.assertj.core.api.objectarray.ObjectArrayAssert_filteredOn_Test:should_fail_if_on_of_the_object_array_element_does_not_have_given_property_or_field
10,org.assertj.core.api.objectarray.ObjectArrayAssert_filteredOn_Test:should_fail_if_filter_operators_are_combined
12,org.assertj.core.api.objectarray.ObjectArrayAssert_filteredOn_Test:should_fail_if_filter_operators_are_combined
1,org.assertj.core.api.objectarray.ObjectArrayAssert_filteredOn_Test:should_fail_if_given_expected_value_is_null
16,org.assertj.core.util.xml.XmlStringPrettyFormatter_prettyFormat_Test:should_throw_error_when_xml_string_is_not_valid
39,org.assertj.core.util.xml.XmlStringPrettyFormatter_prettyFormat_Test:should_throw_error_when_xml_string_is_not_valid
10,org.assertj.core.util.xml.XmlStringPrettyFormatter_prettyFormat_Test:should_throw_error_when_xml_string_is_not_valid
12,org.assertj.core.util.xml.XmlStringPrettyFormatter_prettyFormat_Test:should_throw_error_when_xml_string_is_not_valid
14,org.assertj.core.util.xml.XmlStringPrettyFormatter_prettyFormat_Test:should_throw_error_when_xml_string_is_not_valid
10,org.assertj.core.util.xml.XmlStringPrettyFormatter_prettyFormat_Test:should_throw_error_when_xml_string_is_null
12,org.assertj.core.util.xml.XmlStringPrettyFormatter_prettyFormat_Test:should_throw_error_when_xml_string_is_null
1,org.assertj.core.internal.shortarrays.ShortArrays_assertHasSameSizeAs_with_Array_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValueMatching_Test:should_fail_if_completable_future_was_cancelled
1,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValueMatching_Test:should_fail_if_completable_future_has_failed
16,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValueMatching_Test:should_print_advice_without_description
14,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValueMatching_Test:should_print_advice_without_description
1,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValueMatching_Test:should_fail_when_completable_future_is_null
16,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValueMatching_Test:should_fail_if_result_does_not_match
14,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValueMatching_Test:should_fail_if_result_does_not_match
1,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValueMatching_Test:should_fail_if_completable_future_is_incomplete
1,org.assertj.core.internal.paths.Paths_assertHasSameContentAs_Test:should_fail_if_other_is_not_a_readable_file
1,org.assertj.core.internal.objects.Objects_assertIsEqualToComparingFieldByFieldRecursive_Test:should_have_error_message_with_path_to_difference_when_difference_is_in_collection
1,org.assertj.core.internal.objects.Objects_assertIsEqualToComparingFieldByFieldRecursive_Test:should_have_error_message_with_differences_and_path_to_differences
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isBeforeOrEqualTo_Test:test_isBeforeOrEqual_assertion_error_message
1,org.assertj.core.api.localdate.LocalDateAssert_isNotIn_Test:test_isNotIn_assertion_error_message
66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_pass_if_cause_has_expected_type_and_message
4,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_pass_if_cause_has_expected_type_and_message
68,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_pass_if_cause_has_expected_type_and_message
5,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_pass_if_cause_has_expected_type_and_message
7,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_pass_if_cause_has_expected_type_and_message
63,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_pass_if_cause_has_expected_type_and_message
3,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_no_cause_and_expected_cause_is_not_null
4,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_no_cause_and_expected_cause_is_not_null
5,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_no_cause_and_expected_cause_is_not_null
65,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
3,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
4,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
69,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
6,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
3,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
4,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
69,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
6,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
62,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
3,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
4,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
9,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
3,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
4,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
69,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
6,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
3,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
4,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
69,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
6,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
62,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
16,org.assertj.core.internal.objects.Objects_assertIsEqualToIgnoringNullFields_Test:should_fail_when_one_of_actual_field_to_compare_can_not_be_found_in_the_other_object
14,org.assertj.core.internal.objects.Objects_assertIsEqualToIgnoringNullFields_Test:should_fail_when_one_of_actual_field_to_compare_can_not_be_found_in_the_other_object
1,org.assertj.core.api.localtime.LocalTimeAssert_isEqualToIgnoringNanoseconds_Test:should_fail_if_actual_is_not_equal_to_given_localtimetime_with_nanoseconds_ignored
1,org.assertj.core.api.localtime.LocalTimeAssert_isEqualToIgnoringNanoseconds_Test:should_fail_as_seconds_fields_are_different_even_if_time_difference_is_less_than_a_second
1,org.assertj.core.condition.MatchPredicateTest:should_fail_if_object_does_not_match_predicate_and_use_predicate_description_in_error_message
1,org.assertj.core.condition.MatchPredicateTest:should_fail_if_object_does_not_match_predicate
1,org.assertj.core.internal.booleanarrays.BooleanArrays_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isAfterOrEqualTo_Test:test_isAfterOrEqual_assertion_error_message
16,org.assertj.core.api.filter.Filter_with_property_in_given_values_Test:should_fail_if_elements_to_filter_do_not_have_property_or_field_used_by_filter
14,org.assertj.core.api.filter.Filter_with_property_in_given_values_Test:should_fail_if_elements_to_filter_do_not_have_property_or_field_used_by_filter
1,org.assertj.core.api.filter.Filter_with_property_in_given_values_Test:should_fail_if_property_to_filter_on_is_null
16,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:can_capture_exception_and_then_assert_following_AAA_or_BDD_style
14,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:can_capture_exception_and_then_assert_following_AAA_or_BDD_style
1,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:should_build_ThrowableAssert_with_throwable_thrown
1,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:should_fail_if_no_throwable_was_thrown
0,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:fail_with_good_message_when_assertion_is_failing
16,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:fail_with_good_message_when_assertion_is_failing
14,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:fail_with_good_message_when_assertion_is_failing
1,org.assertj.core.api.Assertions_assertThat_with_Throwable_Test:should_build_ThrowableAssert_with_runtime_exception_thrown
1,org.assertj.core.api.filter.Filter_create_Test:should_fail_if_constructor_array_parameter_is_null
1,org.assertj.core.api.filter.Filter_create_Test:should_fail_if_constructor_iterable_parameter_is_null
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isBeforeOrEqualTo_Test:test_isBeforeOrEqual_assertion_error_message
1,org.assertj.core.api.localdatetime.LocalDateTimeAssert_isIn_Test:test_isIn_assertion_error_message
16,org.assertj.core.api.filter.Filter_with_property_equals_to_given_value_short_version_Test:should_fail_if_elements_to_filter_do_not_have_property_used_by_filter
14,org.assertj.core.api.filter.Filter_with_property_equals_to_given_value_short_version_Test:should_fail_if_elements_to_filter_do_not_have_property_used_by_filter
1,org.assertj.core.api.filter.Filter_with_property_equals_to_given_value_short_version_Test:should_fail_if_property_to_filter_on_is_null
1,org.assertj.core.internal.iterables.Iterables_assertHasSameSizeAs_with_Array_Test:should_fail_if_actual_size_is_not_equal_to_other_size_whatever_custom_comparison_strategy_is
1,org.assertj.core.internal.iterables.Iterables_assertHasSameSizeAs_with_Array_Test:should_fail_if_actual_size_is_not_equal_to_other_size
1,org.assertj.core.internal.objectarrays.ObjectArrays_assertHasOnlyElementsOfType_Test:should_fail_if_one_element_in_actual_does_not_belong_to_the_expected_type
1,org.assertj.core.api.localtime.LocalTimeAssert_isEqualTo_Test:test_isEqualTo_assertion_error_message
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isNotEqualTo_Test:test_isNotEqualTo_assertion_error_message
1,org.assertj.core.api.date.DateAssert_with_string_based_date_representation_Test:use_custom_date_formats_set_from_Assertions_entry_point
1,org.assertj.core.api.date.DateAssert_with_string_based_date_representation_Test:use_custom_date_formats_first_then_defaults_to_parse_a_date
1,org.assertj.core.api.zoneddatetime.ZonedDateTimeAssert_isBeforeOrEqualTo_Test:test_isBeforeOrEqual_assertion_error_message
1,org.assertj.core.api.filter.Filter_with_common_Test:should_fail_if_property_or_field_to_filter_on_is_null
1,org.assertj.core.api.filter.Filter_with_common_Test:should_fail_if_property_or_field_to_filter_on_is_empty
16,org.assertj.core.api.objectarray.ObjectArrayAssert_filteredOn_not_Test:should_fail_if_on_of_the_object_array_element_does_not_have_given_property_or_field
14,org.assertj.core.api.objectarray.ObjectArrayAssert_filteredOn_not_Test:should_fail_if_on_of_the_object_array_element_does_not_have_given_property_or_field
1,org.assertj.core.api.objectarray.ObjectArrayAssert_filteredOn_not_Test:should_fail_if_given_expected_value_is_null
16,org.assertj.core.api.filter.Filter_with_property_equals_to_given_value_Test:should_fail_if_elements_to_filter_do_not_have_property_used_by_filter
14,org.assertj.core.api.filter.Filter_with_property_equals_to_given_value_Test:should_fail_if_elements_to_filter_do_not_have_property_used_by_filter
1,org.assertj.core.api.filter.Filter_with_property_equals_to_given_value_Test:should_fail_if_property_to_filter_on_is_null
1,org.assertj.core.api.future.CompletableFutureAssert_isCancelled_Test:should_fail_when_completable_future_is_null
1,org.assertj.core.api.future.CompletableFutureAssert_isCancelled_Test:should_fail_if_completable_future_is_not_cancelled
52,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_actual_has_no_suppressed_exception_and_expected_suppressed_exception_is_not_null
54,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_actual_has_no_suppressed_exception_and_expected_suppressed_exception_is_not_null
69,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_different_type_and_message_to_expected_cause
50,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_different_type_and_message_to_expected_cause
52,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_different_type_and_message_to_expected_cause
54,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_different_type_and_message_to_expected_cause
56,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_different_type_and_message_to_expected_cause
58,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_different_type_and_message_to_expected_cause
59,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_different_type_and_message_to_expected_cause
62,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_different_type_and_message_to_expected_cause
66,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_pass_if_one_of_the_suppressed_exception_has_the_expected_type_and_message
68,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_pass_if_one_of_the_suppressed_exception_has_the_expected_type_and_message
49,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_pass_if_one_of_the_suppressed_exception_has_the_expected_type_and_message
51,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_pass_if_one_of_the_suppressed_exception_has_the_expected_type_and_message
52,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_pass_if_one_of_the_suppressed_exception_has_the_expected_type_and_message
53,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_pass_if_one_of_the_suppressed_exception_has_the_expected_type_and_message
57,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_pass_if_one_of_the_suppressed_exception_has_the_expected_type_and_message
58,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_pass_if_one_of_the_suppressed_exception_has_the_expected_type_and_message
60,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_pass_if_one_of_the_suppressed_exception_has_the_expected_type_and_message
63,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_pass_if_one_of_the_suppressed_exception_has_the_expected_type_and_message
69,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_not_the_expected_message
50,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_not_the_expected_message
52,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_not_the_expected_message
54,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_not_the_expected_message
56,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_not_the_expected_message
58,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_not_the_expected_message
59,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_not_the_expected_message
62,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_not_the_expected_message
65,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_is_not_instance_of_expected_type
69,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_is_not_instance_of_expected_type
50,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_is_not_instance_of_expected_type
52,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_is_not_instance_of_expected_type
54,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_is_not_instance_of_expected_type
56,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_is_not_instance_of_expected_type
58,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_is_not_instance_of_expected_type
59,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_is_not_instance_of_expected_type
62,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_is_not_instance_of_expected_type
48,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_expected_suppressed_exception_is_null
52,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_no_message_and_the_expected_suppressed_exception_has_one
54,org.assertj.core.internal.throwables.Throwables_assertHasSuppressedException_Test:should_fail_if_suppressed_exception_has_no_message_and_the_expected_suppressed_exception_has_one
1,org.assertj.core.api.zoneddatetime.ZonedDateTimeAssert_isNotEqualTo_errors_Test:test_isNotEqualTo_assertion_error_message
1,org.assertj.core.api.localtime.LocalTimeAssert_isNotIn_Test:test_isNotIn_assertion_error_message
1,org.assertj.core.api.localdatetime.LocalDateTimeAssert_isNotEqualTo_Test:test_isNotEqualTo_assertion_error_message
1,org.assertj.core.internal.strings.Strings_assertHasSameSizeAs_with_CharSequence_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
15,org.assertj.core.internal.throwables.Throwables_assertHasMessageContaining_Test:should_fail_if_actual_has_message_not_containing_with_expected_description
16,org.assertj.core.internal.throwables.Throwables_assertHasMessageContaining_Test:should_pass_if_actual_has_message_containing_with_expected_description
14,org.assertj.core.internal.throwables.Throwables_assertHasMessageContaining_Test:should_pass_if_actual_has_message_containing_with_expected_description
1,org.assertj.core.api.future.CompletableFutureAssert_isCompleted_Test:should_fail_if_completable_future_was_cancelled
1,org.assertj.core.api.future.CompletableFutureAssert_isCompleted_Test:should_fail_if_completable_future_has_failed
1,org.assertj.core.api.future.CompletableFutureAssert_isCompleted_Test:should_fail_when_completable_future_is_null
1,org.assertj.core.api.future.CompletableFutureAssert_isCompleted_Test:should_fail_if_completable_future_is_incomplete
1,org.assertj.core.api.objectarray.ObjectArrayAssert_usingFieldByFieldElementComparator_Test:failed_isEqualTo_assertion_using_field_by_field_element_comparator
1,org.assertj.core.api.objectarray.ObjectArrayAssert_usingFieldByFieldElementComparator_Test:failed_isIn_assertion_using_field_by_field_element_comparator
11,org.assertj.core.internal.throwables.Throwables_assertHasMessageStartingWith_Test:should_fail_if_actual_has_message_not_starting_with_expected_description
10,org.assertj.core.internal.throwables.Throwables_assertHasMessageStartingWith_Test:should_fail_if_actual_has_null_message
12,org.assertj.core.internal.throwables.Throwables_assertHasMessageStartingWith_Test:should_pass_if_actual_has_message_starting_with_expected_description
1,org.assertj.core.condition.ConditionBuiltWithPredicateTest:should_fail_if_condition_is_not_met
16,org.assertj.core.internal.objects.Objects_assertIsEqualToIgnoringGivenFields_Test:should_fail_when_one_of_actual_field_to_compare_can_not_be_found_in_the_other_object
14,org.assertj.core.internal.objects.Objects_assertIsEqualToIgnoringGivenFields_Test:should_fail_when_one_of_actual_field_to_compare_can_not_be_found_in_the_other_object
9,org.assertj.core.internal.throwables.Throwables_assertHasNoCause_Test:should_pass_if_actual_has_no_cause
9,org.assertj.core.internal.throwables.Throwables_assertHasNoCause_Test:should_fail_if_actual_has_a_cause
16,org.assertj.core.navigation.FactoryBasedNavigableIterabelAssert_Test:first_element_navigating_failing_test
14,org.assertj.core.navigation.FactoryBasedNavigableIterabelAssert_Test:first_element_navigating_failing_test
16,org.assertj.core.navigation.FactoryBasedNavigableIterabelAssert_Test:element_navigating_failing_tests
14,org.assertj.core.navigation.FactoryBasedNavigableIterabelAssert_Test:element_navigating_failing_tests
16,org.assertj.core.navigation.FactoryBasedNavigableIterabelAssert_Test:last_element_navigating_failing_test
14,org.assertj.core.navigation.FactoryBasedNavigableIterabelAssert_Test:last_element_navigating_failing_test
1,org.assertj.core.api.objectarray.ObjectArrayAssert_flatExtracting_with_String_parameter_Test:should_throw_exception_when_extracted_value_is_not_an_array_or_an_iterable
1,org.assertj.core.internal.doublearrays.DoubleArrays_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.api.filter.Filter_having_condition_Test:should_fail_if_filter_condition_is_null
1,org.assertj.core.api.throwable.ThrowableAssert_built_from_lambda_Test:should_fail_if_nothing_is_thrown_by_lambda
1,org.assertj.core.api.throwable.ThrowableAssert_built_from_lambda_Test:should_build_ThrowableAssert_with_runtime_exception_thrown_by_lambda
1,org.assertj.core.api.throwable.ThrowableAssert_built_from_lambda_Test:should_build_ThrowableAssert_with_checked_exception_thrown_by_lambda
16,org.assertj.core.navigation.FactoryBasedNavigableListAssert_Test:first_element_navigating_failing_test
14,org.assertj.core.navigation.FactoryBasedNavigableListAssert_Test:first_element_navigating_failing_test
16,org.assertj.core.navigation.FactoryBasedNavigableListAssert_Test:element_navigating_failing_tests
14,org.assertj.core.navigation.FactoryBasedNavigableListAssert_Test:element_navigating_failing_tests
16,org.assertj.core.navigation.FactoryBasedNavigableListAssert_Test:last_element_navigating_failing_test
14,org.assertj.core.navigation.FactoryBasedNavigableListAssert_Test:last_element_navigating_failing_test
34,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_has_no_cause
35,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
34,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
36,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
35,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
1,org.assertj.core.api.future.CompletableFutureAssert_isNotCompletedExceptionally_Test:should_fail_when_completable_future_is_null
1,org.assertj.core.api.future.CompletableFutureAssert_isNotCompletedExceptionally_Test:should_fail_if_completable_future_is_not_completed_exceptionally
1,org.assertj.core.internal.booleanarrays.BooleanArrays_assertHasSameSizeAs_with_Array_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.api.objectarray.ObjectArrayAssert_hasSameSizeAs_with_Arrays_Test:should_fail_if_size_of_actual_has_same_as_other_array
1,org.assertj.core.api.localdate.LocalDateAssert_isEqualTo_Test:test_isEqualTo_assertion_error_message
1,org.assertj.core.api.localtime.LocalTimeAssert_isAfterOrEqualTo_Test:test_isAfterOrEqual_assertion_error_message
1,org.assertj.core.internal.throwables.Throwables_assertHasMessage_Test:should_pass_if_actual_has_expected_message
0,org.assertj.core.internal.throwables.Throwables_assertHasMessage_Test:should_fail_if_actual_has_not_expected_message
16,org.assertj.core.api.objectarray.ObjectArrayAssert_filteredOn_notIn_Test:should_fail_if_on_of_the_object_array_element_does_not_have_given_property_or_field
14,org.assertj.core.api.objectarray.ObjectArrayAssert_filteredOn_notIn_Test:should_fail_if_on_of_the_object_array_element_does_not_have_given_property_or_field
16,org.assertj.core.api.filter.Filter_on_differents_properties_Test:should_fail_if_elements_to_filter_do_not_have_one_of_the_property_or_field_used_by_filter
14,org.assertj.core.api.filter.Filter_on_differents_properties_Test:should_fail_if_elements_to_filter_do_not_have_one_of_the_property_or_field_used_by_filter
1,org.assertj.core.internal.paths.Paths_assertHasFileName_Test:should_fail_if_given_file_name_is_null
16,org.assertj.core.api.iterable.IterableAssert_hasOnlyOneElementSatisfying_Test:fails_if_iterable_has_only_one_element_and_that_element_does_not_statisfy_the_soft_assertion
14,org.assertj.core.api.iterable.IterableAssert_hasOnlyOneElementSatisfying_Test:fails_if_iterable_has_only_one_element_and_that_element_does_not_statisfy_the_soft_assertion
1,org.assertj.core.api.abstract_.AbstractAssert_failWithMessage_Test:should_fail_with_message_having_args
1,org.assertj.core.api.abstract_.AbstractAssert_failWithMessage_Test:should_keep_description_set_by_user
1,org.assertj.core.api.abstract_.AbstractAssert_failWithMessage_Test:should_fail_with_simple_message
1,org.assertj.core.api.abstract_.AbstractAssert_failWithMessage_Test:should_keep_specific_error_message_and_description_set_by_user
1,org.assertj.core.api.localdatetime.LocalDateTimeAssert_isNotIn_Test:test_isNotIn_assertion_error_message
1,org.assertj.core.internal.longarrays.LongArrays_assertHasSameSizeAs_with_Array_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.internal.paths.Paths_assertStartsWith_Test:should_throw_PathsException_if_other_cannot_be_resolved
1,org.assertj.core.internal.paths.Paths_assertStartsWith_Test:should_fail_if_other_is_null
1,org.assertj.core.internal.paths.Paths_assertStartsWith_Test:should_throw_PathsException_if_actual_cannot_be_resolved
1,org.assertj.core.api.zoneddatetime.ZonedDateTimeAssert_isEqualToIgnoringHours_Test:should_pass_if_actual_is_equal_to_other_ignoring_hours_in_different_timezone
1,org.assertj.core.api.zoneddatetime.ZonedDateTimeAssert_isEqualToIgnoringHours_Test:should_fail_if_actual_is_not_equal_to_given_datetime_with_hours_ignored
27,org.assertj.core.internal.throwables.Throwables_assertHasMessageEnding_Test:should_pass_if_actual_has_message_ending_with_expected_description
29,org.assertj.core.internal.throwables.Throwables_assertHasMessageEnding_Test:should_pass_if_actual_has_message_ending_with_expected_description
28,org.assertj.core.internal.throwables.Throwables_assertHasMessageEnding_Test:should_fail_if_actual_has_message_not_ending_with_expected_description
1,org.assertj.core.api.zoneddatetime.ZonedDateTimeAssert_isNotIn_errors_Test:test_isNotIn_assertion_error_message
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isEqualToIgnoringTimezone_Test:should_fail_if_actual_is_not_equal_to_given_OffsetTime_with_timezone_ignored
1,org.assertj.core.api.localdate.LocalDateAssert_isAfter_Test:test_isAfter_assertion_error_message
1,org.assertj.core.util.Introspection_getProperty_Test:should_raise_an_error_because_of_non_public_getter
1,org.assertj.core.util.Introspection_getProperty_Test:should_raise_an_error_because_of_non_public_getter_when_getter_is_in_superclass
1,org.assertj.core.util.Introspection_getProperty_Test:should_raise_an_error_because_of_missing_getter
1,org.assertj.core.internal.floatarrays.FloatArrays_assertHasSameSizeAs_with_Array_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.internal.iterables.Iterables_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_actual_size_is_not_equal_to_other_size_whatever_custom_comparison_strategy_is
1,org.assertj.core.internal.iterables.Iterables_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_actual_size_is_not_equal_to_other_size
1,org.assertj.core.internal.paths.Paths_assertHasNoParent_Test:should_throw_PathsException_if_actual_cannot_be_canonicalized
1,org.assertj.core.internal.maps.Maps_assertHasSameSizeAs_with_Array_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
0,org.assertj.core.api.AutoCloseableSoftAssertionsTest:should_be_able_to_catch_exceptions_thrown_by_all_proxied_methods
23,org.assertj.core.internal.throwables.Throwables_assertHasMessageMatching_Test:should_pass_if_throwable_message_is_empty_and_regex_is_too
25,org.assertj.core.internal.throwables.Throwables_assertHasMessageMatching_Test:should_pass_if_throwable_message_is_empty_and_regex_is_too
1,org.assertj.core.internal.throwables.Throwables_assertHasMessageMatching_Test:should_fail_if_given_regex_is_null
22,org.assertj.core.internal.throwables.Throwables_assertHasMessageMatching_Test:should_fail_if_given_regex_is_null
24,org.assertj.core.internal.throwables.Throwables_assertHasMessageMatching_Test:should_fail_if_throwable_message_does_not_match_given_regex
23,org.assertj.core.internal.throwables.Throwables_assertHasMessageMatching_Test:should_fail_if_throwable_does_not_have_a_message
23,org.assertj.core.internal.throwables.Throwables_assertHasMessageMatching_Test:should_pass_if_throwable_message_matches_given_regex
25,org.assertj.core.internal.throwables.Throwables_assertHasMessageMatching_Test:should_pass_if_throwable_message_matches_given_regex
16,org.assertj.core.api.Java6JUnitSoftAssertionsFailureTest:should_report_all_errors
14,org.assertj.core.api.Java6JUnitSoftAssertionsFailureTest:should_report_all_errors
16,org.assertj.core.api.SoftAssertionsTest:should_assert_using_assertSoftly
14,org.assertj.core.api.SoftAssertionsTest:should_assert_using_assertSoftly
0,org.assertj.core.api.SoftAssertionsTest:should_be_able_to_catch_exceptions_thrown_by_all_proxied_methods
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isNotIn_Test:test_isNotIn_assertion_error_message
19,org.assertj.core.internal.throwables.Throwables_assertHasStackTraceContaining_Test:should_fail_if_actual_has_stacktrace_not_containing_the_expected_description
18,org.assertj.core.internal.throwables.Throwables_assertHasStackTraceContaining_Test:should_pass_if_actual_has_stacktrace_containing_the_expected_description
20,org.assertj.core.internal.throwables.Throwables_assertHasStackTraceContaining_Test:should_pass_if_actual_has_stacktrace_containing_the_expected_description
1,org.assertj.core.api.iterable.IterableAssert_usingFieldByFieldElementComparator_Test:failed_isEqualTo_assertion_using_field_by_field_element_comparator
1,org.assertj.core.api.iterable.IterableAssert_usingFieldByFieldElementComparator_Test:failed_isIn_assertion_using_field_by_field_element_comparator
1,org.assertj.core.internal.paths.Paths_assertEndsWithRaw_Test:should_fail_if_other_is_null
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isEqualTo_Test:test_isEqualTo_assertion_error_message
1,org.assertj.core.api.offsettime.OffsetTimeAssert_hasSameHourAs_Test:should_fail_as_minutes_fields_are_different_even_if_time_difference_is_less_than_a_minute
1,org.assertj.core.api.offsettime.OffsetTimeAssert_hasSameHourAs_Test:should_fail_if_actual_is_not_equal_to_given_offsetTime_with_minute_ignored
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isIn_Test:test_isIn_assertion_error_message
1,org.assertj.core.internal.chararrays.CharArrays_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.api.localtime.LocalTimeAssert_isBeforeOrEqualTo_Test:test_isBeforeOrEqual_assertion_error_message
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isIn_Test:test_isIn_assertion_error_message
66,org.assertj.core.api.throwable.ThrowableAssert_hasSuppressedException_Test:invoke_api_like_user
68,org.assertj.core.api.throwable.ThrowableAssert_hasSuppressedException_Test:invoke_api_like_user
49,org.assertj.core.api.throwable.ThrowableAssert_hasSuppressedException_Test:invoke_api_like_user
51,org.assertj.core.api.throwable.ThrowableAssert_hasSuppressedException_Test:invoke_api_like_user
52,org.assertj.core.api.throwable.ThrowableAssert_hasSuppressedException_Test:invoke_api_like_user
53,org.assertj.core.api.throwable.ThrowableAssert_hasSuppressedException_Test:invoke_api_like_user
57,org.assertj.core.api.throwable.ThrowableAssert_hasSuppressedException_Test:invoke_api_like_user
58,org.assertj.core.api.throwable.ThrowableAssert_hasSuppressedException_Test:invoke_api_like_user
60,org.assertj.core.api.throwable.ThrowableAssert_hasSuppressedException_Test:invoke_api_like_user
63,org.assertj.core.api.throwable.ThrowableAssert_hasSuppressedException_Test:invoke_api_like_user
16,org.assertj.core.internal.objects.Objects_assertIsEqualToComparingOnlyGivenFields_Test:should_fail_when_one_of_actual_field_to_compare_can_not_be_found_in_the_other_object
14,org.assertj.core.internal.objects.Objects_assertIsEqualToComparingOnlyGivenFields_Test:should_fail_when_one_of_actual_field_to_compare_can_not_be_found_in_the_other_object
1,org.assertj.core.api.future.CompletableFutureAssert_isCompletedExceptionally_Test:should_fail_when_completable_future_is_null
1,org.assertj.core.api.future.CompletableFutureAssert_isCompletedExceptionally_Test:should_fail_if_completable_future_is_not_completed_exceptionally
1,org.assertj.core.internal.intarrays.IntArrays_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.internal.objectarrays.ObjectArrays_assertHasAtLeastOneElementOfType_Test:should_fail_if_no_elements_in_actual_belongs_to_the_expected_type
1,org.assertj.core.internal.doubles.Doubles_assertEqual_double_with_offset_Test:should_fail_if_second_double_is_null_but_not_the_first_whatever_custom_comparison_strategy_is
1,org.assertj.core.internal.doubles.Doubles_assertEqual_double_with_offset_Test:should_fail_if_second_double_is_null_but_not_the_first
1,org.assertj.core.api.localdate.LocalDateAssert_isToday_Test:test_isToday_assertion_error_message
1,org.assertj.core.internal.objectarrays.ObjectArrays_assertHasSameSizeAs_with_Array_Test:should_fail_if_actual_size_is_not_equal_to_other_size
1,org.assertj.core.api.filter.Filter_being_condition_Test:should_fail_if_filter_condition_is_null
1,org.assertj.core.util.Preconditions_checkArgument_Test:should_throw_nullpointerexception_if_object_is_null
1,org.assertj.core.api.localdate.LocalDateAssert_isIn_Test:test_isIn_assertion_error_message
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isAfter_Test:test_isAfter_assertion_error_message
1,org.assertj.core.api.localtime.LocalTimeAssert_hasSameHourAs_Test:should_fail_as_minutes_fields_are_different_even_if_time_difference_is_less_than_a_minute
1,org.assertj.core.api.localtime.LocalTimeAssert_hasSameHourAs_Test:should_fail_if_actual_is_not_equal_to_given_localtimetime_with_minute_ignored
1,org.assertj.core.internal.strings.Strings_assertHasSize_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.internal.strings.Strings_assertHasSize_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size_whatever_custom_comparison_strategy_is
1,org.assertj.core.internal.bytearrays.ByteArrays_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.internal.strings.Strings_assertHasSameSizeAs_with_Array_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.api.localtime.LocalTimeAssert_isAfter_Test:test_isAfter_assertion_error_message
1,org.assertj.core.api.localtime.LocalTimeAssert_isIn_Test:test_isIn_assertion_error_message
16,org.assertj.core.api.Assertions_useRepresentation_Test:should_use_given_representation_in_assertion_error_messages
14,org.assertj.core.api.Assertions_useRepresentation_Test:should_use_given_representation_in_assertion_error_messages
16,org.assertj.core.api.date.DateAssert_setLenientDateParsing:should_fail_if_date_can_be_parsed_leniently_but_lenient_mode_is_disabled
14,org.assertj.core.api.date.DateAssert_setLenientDateParsing:should_fail_if_date_can_be_parsed_leniently_but_lenient_mode_is_disabled
1,org.assertj.core.api.localtime.LocalTimeAssert_isEqualToIgnoringSeconds_Test:should_fail_as_seconds_fields_are_different_even_if_time_difference_is_less_than_a_second
1,org.assertj.core.api.localtime.LocalTimeAssert_isEqualToIgnoringSeconds_Test:should_fail_if_actual_is_not_equal_to_given_localtimetime_with_second_ignored
1,org.assertj.core.api.object.ObjectAssert_hasFieldOrPropertyWithValue_Test:shoud_fail_if_given_field_or_property_name_is_null
1,org.assertj.core.api.object.ObjectAssert_hasFieldOrPropertyWithValue_Test:shoud_fail_if_field_or_property_value_is_not_equal_to_the_expected_value
1,org.assertj.core.api.object.ObjectAssert_hasFieldOrPropertyWithValue_Test:shoud_fail_if_given_field_or_property_does_not_exist
1,org.assertj.core.api.object.ObjectAssert_hasFieldOrPropertyWithValue_Test:shoud_fail_when_property_or_field_value_is_null_and_expected_value_is_not
1,org.assertj.core.api.object.ObjectAssert_hasFieldOrPropertyWithValue_Test:shoud_fail_if_field_or_property_value_is_not_null_when_expected_value_is
1,org.assertj.core.internal.intarrays.IntArrays_assertHasSameSizeAs_with_Array_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isBefore_Test:test_isBefore_assertion_error_message
1,org.assertj.core.api.future.CompletableFutureAssert_isNotCancelled_Test:should_fail_when_completable_future_is_null
1,org.assertj.core.api.future.CompletableFutureAssert_isNotCancelled_Test:should_fail_if_completable_future_is_not_cancelled
1,org.assertj.core.internal.paths.Paths_assertEndsWith_Test:should_fail_with_PathsException_if_actual_cannot_be_resolved
1,org.assertj.core.internal.paths.Paths_assertEndsWith_Test:should_fail_if_other_is_null
1,org.assertj.core.api.zoneddatetime.ZonedDateTimeAssert_isAfter_Test:test_isAfter_assertion_error_message
1,org.assertj.core.internal.objectarrays.ObjectArrays_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_actual_size_is_not_equal_to_other_size
1,org.assertj.core.api.iterable.IterableAssert_flatExtracting_with_String_parameter_Test:should_throw_exception_when_extracted_value_is_not_an_array_or_an_iterable
1,org.assertj.core.internal.paths.Paths_assertHasParentRaw_Test:should_fail_if_provided_parent_is_null
0,org.assertj.core.api.AutoCloseableBDDSoftAssertionsTest:should_be_able_to_catch_exceptions_thrown_by_all_proxied_methods
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isEqualTo_Test:test_isEqualTo_assertion_error_message
1,org.assertj.core.internal.maps.Maps_assertContainsExactly_Test:should_fail_if_actual_and_expected_entries_have_different_size
38,org.assertj.core.internal.throwables.Throwables_assertHasRootCauseInstanceOf_Test:should_fail_if_actual_has_no_cause
39,org.assertj.core.internal.throwables.Throwables_assertHasRootCauseInstanceOf_Test:should_pass_if_root_cause_is_instance_of_expected_type
39,org.assertj.core.internal.throwables.Throwables_assertHasRootCauseInstanceOf_Test:should_pass_if_root_cause_is_exactly_instance_of_expected_type
38,org.assertj.core.internal.throwables.Throwables_assertHasRootCauseInstanceOf_Test:should_fail_if_root_cause_is_not_instance_of_expected_type
1,org.assertj.core.error.ConstructorInvoker_newInstance_Test:should_create_Object_using_reflection
1,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_fail_if_nothing_is_thrown_by_lambda
9,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_build_ExpectThrowableAssert_with_exception_thrown_by_lambda
1,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
10,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
12,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
18,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
20,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
23,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
25,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
27,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
29,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
32,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
34,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
36,org.assertj.core.api.throwable.ExpectThrowableAssert_isThrownBy_Test:should_allow_to_check_exception_thrown_by_lambda
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isEqualToIgnoringTimezone_Test:should_fail_if_actual_is_not_equal_to_given_OffsetDateTime_with_timezone_ignored
1,org.assertj.core.api.array.AbstractEnumerableAssert_hasSameSizeAs_with_Array_Test:should_fail_if_size_of_actual_has_same_as_other_array
1,org.assertj.core.internal.floatarrays.FloatArrays_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.api.abstract_.AbstractAssert_isInstanceOfSatisfying_Test:should_fail_according_to_requirements
1,org.assertj.core.api.localdatetime.LocalDateTimeAssert_isBeforeOrEqualTo_Test:test_isBeforeOrEqual_assertion_error_message
1,org.assertj.core.api.zoneddatetime.ZonedDateTimeAssert_isAfterOrEqualTo_Test:test_isAfterOrEqual_assertion_error_message
1,org.assertj.core.internal.maps.Maps_assertHasSameSizeAs_with_Map_Test:should_fail_if_size_of_actual_is_not_equal_to_size_of_other
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isEqualToIgnoringHours_Test:should_fail_if_actual_is_not_equal_to_given_offsetdatetime_with_hour_ignored
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isEqualToIgnoringHours_Test:should_fail_as_hours_fields_are_different_even_if_time_difference_is_less_than_a_hour
1,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_was_cancelled
1,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_when_completable_future_is_null
1,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_is_completed
1,org.assertj.core.api.future.CompletableFutureAssert_hasFailed_Test:should_fail_if_completable_future_is_incomplete
16,org.assertj.core.api.abstract_.AbstractAssert_withRepresentation_Test:should_be_able_to_override_an_existing_representation
14,org.assertj.core.api.abstract_.AbstractAssert_withRepresentation_Test:should_be_able_to_override_an_existing_representation
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isEqualToIgnoringSeconds_Test:should_fail_as_seconds_fields_are_different_even_if_time_difference_is_less_than_a_second
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isEqualToIgnoringSeconds_Test:should_fail_if_actual_is_not_equal_to_given_offsetTime_with_second_ignored
1,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_was_cancelled
1,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_when_completable_future_is_null
1,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_is_completed
16,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_has_failed_with_wrong_throwable
14,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_has_failed_with_wrong_throwable
1,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_pass_if_completable_future_has_failed
1,org.assertj.core.api.future.CompletableFutureAssert_hasFailedWithThrowableThat_Test:should_fail_if_completable_future_is_incomplete
1,org.assertj.core.internal.maps.Maps_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
41,org.assertj.core.internal.throwables.Throwables_assertHasRootCauseExactlyInstanceOf_Test:should_fail_if_actual_has_no_cause
41,org.assertj.core.internal.throwables.Throwables_assertHasRootCauseExactlyInstanceOf_Test:should_pass_if_root_cause_is_exactly_instance_of_expected_type
43,org.assertj.core.internal.throwables.Throwables_assertHasRootCauseExactlyInstanceOf_Test:should_pass_if_root_cause_is_exactly_instance_of_expected_type
42,org.assertj.core.internal.throwables.Throwables_assertHasRootCauseExactlyInstanceOf_Test:should_fail_if_root_cause_is_not_instance_of_expected_type
42,org.assertj.core.internal.throwables.Throwables_assertHasRootCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isAfter_Test:test_isAfter_assertion_error_message
1,org.assertj.core.api.throwable.ThrowableAssert_built_with_then_method_Test:should_fail_if_nothing_is_thrown_by_callable_code
1,org.assertj.core.api.throwable.ThrowableAssert_built_with_then_method_Test:should_build_ThrowableAssert_with_throwable_thrown_by_callable_code
1,org.assertj.core.api.throwable.ThrowableAssert_built_with_then_method_Test:should_build_ThrowableAssert_with_runtime_exception_thrown_by_callable_code
1,org.assertj.core.api.localdate.LocalDateAssert_isNotEqualTo_Test:test_isNotEqualTo_assertion_error_message
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isAfterOrEqualTo_Test:test_isAfterOrEqual_assertion_error_message
1,org.assertj.core.api.localtime.LocalTimeAssert_isNotEqualTo_Test:test_isNotEqualTo_assertion_error_message
12,org.assertj.core.internal.files.Files_assertSameContentAs_Test:should_throw_an_error_if_files_cant_be_compared_with_the_given_charsets_even_if_binary_identical
1,org.assertj.core.api.zoneddatetime.ZonedDateTimeAssert_isBefore_Test:test_isBefore_assertion_error_message
1,org.assertj.core.api.localtime.LocalTimeAssert_isBefore_Test:test_isBefore_assertion_error_message
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isBefore_Test:test_isBefore_assertion_error_message
16,org.assertj.core.api.iterable.IterableAssert_filteredOn_not_Test:should_fail_if_on_of_the_iterable_element_does_not_have_given_property_or_field
14,org.assertj.core.api.iterable.IterableAssert_filteredOn_not_Test:should_fail_if_on_of_the_iterable_element_does_not_have_given_property_or_field
1,org.assertj.core.api.iterable.IterableAssert_filteredOn_not_Test:should_fail_if_given_expected_value_is_null
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isEqualToIgnoringNanoseconds_Test:should_fail_if_actual_is_not_equal_to_given_OffsetTime_with_nanoseconds_ignored
1,org.assertj.core.api.offsettime.OffsetTimeAssert_isEqualToIgnoringNanoseconds_Test:should_fail_as_seconds_fields_are_different
1,org.assertj.core.api.throwable.ThrowableAssert_built_from_ThrowingCallable_Test:should_fail_if_nothing_is_thrown_by_callable_code
1,org.assertj.core.api.throwable.ThrowableAssert_built_from_ThrowingCallable_Test:should_build_ThrowableAssert_with_throwable_thrown_by_callable_code
1,org.assertj.core.api.throwable.ThrowableAssert_built_from_ThrowingCallable_Test:should_build_ThrowableAssert_with_runtime_exception_thrown_by_callable_code
45,org.assertj.core.internal.throwables.Throwables_assertHasNoSuppressedExceptions_Test:should_pass_if_throwable_has_no_suppressed_exceptions
46,org.assertj.core.internal.throwables.Throwables_assertHasNoSuppressedExceptions_Test:should_fail_if_throwable_has_suppressed_exceptions
1,org.assertj.core.internal.paths.Paths_assertStartsWithRaw_Test:should_fail_if_other_is_null
16,org.assertj.core.api.objectarray.ObjectArrayAssert_filteredOn_in_Test:should_fail_if_on_of_the_object_array_element_does_not_have_given_property_or_field
14,org.assertj.core.api.objectarray.ObjectArrayAssert_filteredOn_in_Test:should_fail_if_on_of_the_object_array_element_does_not_have_given_property_or_field
16,org.assertj.core.api.filter.Filter_with_property_not_in_given_values_Test:should_fail_if_elements_to_filter_do_not_have_property_used_by_filter
14,org.assertj.core.api.filter.Filter_with_property_not_in_given_values_Test:should_fail_if_elements_to_filter_do_not_have_property_used_by_filter
1,org.assertj.core.api.filter.Filter_with_property_not_in_given_values_Test:should_fail_if_property_to_filter_on_is_null
1,org.assertj.core.internal.maps.Maps_assertHasSize_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isEqualToIgnoringMinutes_Test:should_fail_as_minutes_fields_are_different_even_if_time_difference_is_less_than_a_minute
1,org.assertj.core.api.offsetdatetime.OffsetDateTimeAssert_isEqualToIgnoringMinutes_Test:should_fail_if_actual_is_not_equal_to_given_offsetdatetime_with_minute_ignored
1,org.assertj.core.internal.paths.Paths_assertHasParent_Test:should_fail_if_expected_parent_cannot_be_canonicalized
1,org.assertj.core.internal.paths.Paths_assertHasParent_Test:should_fail_if_actual_cannot_be_canonicalized
1,org.assertj.core.internal.paths.Paths_assertHasParent_Test:should_fail_if_given_parent_is_null
1,org.assertj.core.internal.strings.Strings_assertHasLinesCount_Test:should_fail_if_lines_count_of_actual_is_not_equal_to_expected_lines_count_whatever_custom_comparison_strategy_is
1,org.assertj.core.internal.strings.Strings_assertHasLinesCount_Test:should_fail_if_lines_count_of_actual_is_not_equal_to_expected_size
45,org.assertj.core.api.throwable.ThrowableAssert_hasNoSuppressedExceptions_Test:invoke_api_like_user
1,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValue_Test:should_fail_if_completable_future_was_cancelled
1,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValue_Test:should_fail_if_completable_future_has_failed
1,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValue_Test:should_fail_when_completable_future_is_null
16,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValue_Test:should_fail_if_result_does_not_match
14,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValue_Test:should_fail_if_result_does_not_match
1,org.assertj.core.api.future.CompletableFutureAssert_isCompletedWithValue_Test:should_fail_if_completable_future_is_incomplete
1,org.assertj.core.api.future.CompletableFutureAssert_isDone_Test:should_fail_if_completable_future_is_not_done
1,org.assertj.core.api.future.CompletableFutureAssert_isDone_Test:should_fail_when_completable_future_is_null
1,org.assertj.core.internal.shortarrays.ShortArrays_assertHasSameSizeAs_with_Iterable_Test:should_fail_if_size_of_actual_is_not_equal_to_expected_size
10,org.assertj.core.api.iterable.IterableAssert_filteredOn_Test:should_fail_if_filter_operators_are_combined
12,org.assertj.core.api.iterable.IterableAssert_filteredOn_Test:should_fail_if_filter_operators_are_combined
16,org.assertj.core.api.iterable.IterableAssert_filteredOn_Test:should_fail_if_on_of_the_iterable_element_does_not_have_given_property_or_field
14,org.assertj.core.api.iterable.IterableAssert_filteredOn_Test:should_fail_if_on_of_the_iterable_element_does_not_have_given_property_or_field
1,org.assertj.core.api.iterable.IterableAssert_filteredOn_Test:should_fail_if_given_expected_value_is_null
1,org.assertj.core.api.localdate.LocalDateAssert_isAfterOrEqualTo_Test:test_isAfterOrEqual_assertion_error_message
