0,20,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_no_cause_and_expected_cause_is_not_null
32,53,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_no_cause_and_expected_cause_is_not_null
2,22,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_no_cause_and_expected_cause_is_not_null
26,47,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_no_cause_and_expected_cause_is_not_null
27,47,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_no_cause_and_expected_cause_is_not_null
28,47,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_no_cause_and_expected_cause_is_not_null
29,47,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_no_cause_and_expected_cause_is_not_null
30,47,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_no_cause_and_expected_cause_is_not_null
31,47,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_no_cause_and_expected_cause_is_not_null
0,20,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_is_null
32,53,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_is_null
2,22,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_is_null
26,47,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_is_null
27,47,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_is_null
28,47,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_is_null
29,47,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_is_null
30,47,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_is_null
31,47,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_is_null
0,20,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
33,57,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
2,22,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
34,57,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
3,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
35,57,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
4,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
36,57,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
5,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
37,57,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
38,57,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
39,62,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_is_not_instance_of_expected_type
0,20,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
33,57,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
2,22,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
34,57,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
3,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
35,57,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
4,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
36,57,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
5,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
37,57,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
38,57,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
6,27,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
39,62,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
7,27,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
8,27,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
40,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
41,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
42,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
43,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
44,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
45,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
46,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_no_message_and_the_expected_cause_has_one
0,20,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
2,22,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
3,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
4,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
5,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
6,27,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
7,27,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
8,27,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
40,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
41,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
42,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
43,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
44,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
45,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
46,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_actual_has_cause_and_expected_cause_is_null
0,20,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
2,22,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
3,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
4,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
5,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
6,27,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
7,27,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
8,27,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
9,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
10,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
11,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
12,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
13,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
14,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
15,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
16,42,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
17,42,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
18,42,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
19,42,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
20,42,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
21,43,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
22,43,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
23,43,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
24,43,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
25,43,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_different_type_and_message_to_expected_cause
0,20,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
2,22,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
3,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
4,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
5,24,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
6,27,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
7,27,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
8,27,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
9,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
10,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
11,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
12,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
13,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
14,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
15,33,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
16,42,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
17,42,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
18,42,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
19,42,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
20,42,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
21,43,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
22,43,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
23,43,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
24,43,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
25,43,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
40,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
41,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
42,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
43,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
44,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
45,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
46,66,org.assertj.core.internal.throwables.Throwables_assertHasCause_Test:should_fail_if_cause_has_not_the_expected_message
0,20,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
2,22,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
3,24,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
4,24,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
5,24,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
6,27,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
7,27,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
8,27,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
40,66,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
41,66,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
42,66,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
43,66,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
44,66,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
45,66,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
46,66,org.assertj.core.internal.iterables.Iterables_assertContainsSubsequence_Test:should_pass_if_actual_contains_subsequence_according_to_custom_comparison_strategy
